### PR TITLE
feat: Compatible with Chinese

### PR DESCRIPTION
**Pull request by yklydxtt**
image   
I made this change,handle Chinese

### CODE REVIEW

**Comment by caio-ribeiro-pereira** [comment]
@yklydxtt your code has some lint error, please fix it, so I can accept your PR, thanks

**Comment by yklydxtt** [comment]
> @yklydxtt your code has some lint error, please fix it, so I can accept your PR, thanks

I fixed it

**Comment by caio-ribeiro-pereira** [comment]
@yklydxtt one question: is this function is for bypass chinese chars only or is for any other special chars?

**Comment by yklydxtt** [comment]
> @yklydxtt one question: is this function is for bypass chinese chars only or is for any other special chars? Because if this function can ignore others chars, I suggest to rename the function and the test to "hasSpecialChars" instead "hasChinese"

only for chinese chars

**Comment by caio-ribeiro-pereira** [comment]
Okay, thanks for this PR, I will update soon this lib

**Comment by caio-ribeiro-pereira** [comment]
@yklydxtt lib updated to [0.0.9](https://www.npmjs.com/package/field-normalizer/v/0.0.9) on npm with your PR and few improvements mine, thank you!

**Pull request merged**
